name: CI
on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set execute permission for gradlew
        run: chmod +x gradlew
      - name: Build project
        run: ./gradlew clean build
  
  checkstyle:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          checkstyle_config: './checkstyle.xml'
          fail_on_error: true
          token: ${{ secrets.GITHUB_TOKEN }}

  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set execute permission for gradlew
        run: chmod +x gradlew
      - name: Jacoco
        run: ./gradlew test jacocoTestReport
      - name: Upload coverage report
        uses: madrapps/jacoco-report@v1.6.1
        with:
          title: Coverage report
          paths: ${{ github.workspace }}/**/build/reports/jacoco/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
